# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(675, 458)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 130, 461, 178))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.klapan_2_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.klapan_2_max.setMaximumSize(QtCore.QSize(98, 30))
        self.klapan_2_max.setObjectName("klapan_2_max")
        self.gridLayout.addWidget(self.klapan_2_max, 2, 4, 1, 1)
        self.klapan_1_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.klapan_1_max.setMaximumSize(QtCore.QSize(98, 30))
        self.klapan_1_max.setObjectName("klapan_1_max")
        self.gridLayout.addWidget(self.klapan_1_max, 1, 4, 1, 1)
        self.klapan_2_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.klapan_2_min.setMaximumSize(QtCore.QSize(98, 30))
        self.klapan_2_min.setObjectName("klapan_2_min")
        self.gridLayout.addWidget(self.klapan_2_min, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.klapan_3_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.klapan_3_max.setMaximumSize(QtCore.QSize(98, 30))
        self.klapan_3_max.setObjectName("klapan_3_max")
        self.gridLayout.addWidget(self.klapan_3_max, 3, 4, 1, 1)
        self.klapan_3_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.klapan_3_min.setMaximumSize(QtCore.QSize(98, 30))
        self.klapan_3_min.setObjectName("klapan_3_min")
        self.gridLayout.addWidget(self.klapan_3_min, 3, 2, 1, 1)
        self.klapan_4_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.klapan_4_min.setMaximumSize(QtCore.QSize(98, 30))
        self.klapan_4_min.setObjectName("klapan_4_min")
        self.gridLayout.addWidget(self.klapan_4_min, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.valve_1 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.valve_1.setMaximumSize(QtCore.QSize(98, 30))
        self.valve_1.setObjectName("valve_1")
        self.gridLayout.addWidget(self.valve_1, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.valve_2 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.valve_2.setMaximumSize(QtCore.QSize(98, 30))
        self.valve_2.setObjectName("valve_2")
        self.gridLayout.addWidget(self.valve_2, 2, 1, 1, 1)
        self.klapan_1_min = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.klapan_1_min.setMaximumSize(QtCore.QSize(98, 30))
        self.klapan_1_min.setObjectName("klapan_1_min")
        self.gridLayout.addWidget(self.klapan_1_min, 1, 2, 1, 1)
        self.klapan_4_max = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.klapan_4_max.setMaximumSize(QtCore.QSize(98, 30))
        self.klapan_4_max.setObjectName("klapan_4_max")
        self.gridLayout.addWidget(self.klapan_4_max, 4, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.ip_adress = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ip_adress.setObjectName("ip_adress")
        self.gridLayout.addWidget(self.ip_adress, 1, 5, 1, 1)
        self.datchicki = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.datchicki.setObjectName("datchicki")
        self.gridLayout.addWidget(self.datchicki, 2, 5, 1, 1)
        self.i_o_manage = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.i_o_manage.setObjectName("i_o_manage")
        self.gridLayout.addWidget(self.i_o_manage, 3, 5, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Min"))
        self.label_3.setText(_translate("Dialog", "Насос 1"))
        self.label_4.setText(_translate("Dialog", "Насос 2"))
        self.label_2.setText(_translate("Dialog", "Max"))
        self.ip_adress.setText(_translate("Dialog", "IP адрес"))
        self.datchicki.setText(_translate("Dialog", "Настройка датчиков"))
        self.i_o_manage.setText(_translate("Dialog", "Ручное управление Вход-Выход"))
