# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from pymodbus.client.sync import ModbusTcpClient
from settings import ip
from utilites import Utilites


class Ui_Vacuum(object):
    def setupUi(self, Vacuum):
        Vacuum.setObjectName("Vacuum")
        Vacuum.resize(576, 222)
        Vacuum.setMaximumSize(QtCore.QSize(618, 264))
        self.gridLayoutWidget = QtWidgets.QWidget(Vacuum)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 251, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Vacuum)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(290, 45, 260, 150))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.plainTextEdit_3.setMaximumSize(QtCore.QSize(73, 35))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_2.addWidget(self.plainTextEdit_3, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Vacuum)
        self.label_5.setGeometry(QtCore.QRect(190, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Vacuum)
        QtCore.QMetaObject.connectSlotsByName(Vacuum)
        try:
            self.client = ModbusTcpClient(ip)
            self.client.connect()
        except:
            pass


    def retranslateUi(self, Vacuum):
        _translate = QtCore.QCoreApplication.translate
        Vacuum.setWindowTitle(_translate("Vacuum", "Dialog"))
        self.label_2.setText(_translate("Vacuum", "Необходимый адрес"))
        self.label.setText(_translate("Vacuum", "Текущий адрес"))
        self.pushButton_7.setText(_translate("Vacuum", "Установить"))
        self.pushButton_5.setText(_translate("Vacuum", "Установить"))
        self.pushButton_2.setText(_translate("Vacuum", "Torr"))
        self.pushButton_3.setText(_translate("Vacuum", "mbar"))
        self.label_4.setText(_translate("Vacuum", "Адрес"))
        self.pushButton_4.setText(_translate("Vacuum", "Pascal"))
        self.label_3.setText(_translate("Vacuum", "Настройка размерности измерения"))
        self.label_5.setText(_translate("Vacuum", "Настройки дачиков вакуума"))
